version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: training_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build: .
    container_name: training_app
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./app:/app/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: training_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: training_certbot
    restart: "no"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge